INSERT INTO Status (StatusID, Status) VALUES (1, '"Finished"');
INSERT INTO Status (StatusID, Status) VALUES (2, '"Disqualified"');
INSERT INTO Status (StatusID, Status) VALUES (3, '"Accident"');
INSERT INTO Status (StatusID, Status) VALUES (4, '"Collision"');
INSERT INTO Status (StatusID, Status) VALUES (5, '"Engine"');
INSERT INTO Status (StatusID, Status) VALUES (6, '"Gearbox"');
INSERT INTO Status (StatusID, Status) VALUES (7, '"Transmission"');
INSERT INTO Status (StatusID, Status) VALUES (8, '"Clutch"');
INSERT INTO Status (StatusID, Status) VALUES (9, '"Hydraulics"');
INSERT INTO Status (StatusID, Status) VALUES (10, '"Electrical"');
INSERT INTO Status (StatusID, Status) VALUES (11, '"+1 Lap"');
INSERT INTO Status (StatusID, Status) VALUES (12, '"+2 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (13, '"+3 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (14, '"+4 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (15, '"+5 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (16, '"+6 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (17, '"+7 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (18, '"+8 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (19, '"+9 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (20, '"Spun off"');
INSERT INTO Status (StatusID, Status) VALUES (21, '"Radiator"');
INSERT INTO Status (StatusID, Status) VALUES (22, '"Suspension"');
INSERT INTO Status (StatusID, Status) VALUES (23, '"Brakes"');
INSERT INTO Status (StatusID, Status) VALUES (24, '"Differential"');
INSERT INTO Status (StatusID, Status) VALUES (25, '"Overheating"');
INSERT INTO Status (StatusID, Status) VALUES (26, '"Mechanical"');
INSERT INTO Status (StatusID, Status) VALUES (27, '"Tyre"');
INSERT INTO Status (StatusID, Status) VALUES (28, '"Driver Seat"');
INSERT INTO Status (StatusID, Status) VALUES (29, '"Puncture"');
INSERT INTO Status (StatusID, Status) VALUES (30, '"Driveshaft"');
INSERT INTO Status (StatusID, Status) VALUES (31, '"Retired"');
INSERT INTO Status (StatusID, Status) VALUES (32, '"Fuel pressure"');
INSERT INTO Status (StatusID, Status) VALUES (33, '"Front wing"');
INSERT INTO Status (StatusID, Status) VALUES (34, '"Water pressure"');
INSERT INTO Status (StatusID, Status) VALUES (35, '"Refuelling"');
INSERT INTO Status (StatusID, Status) VALUES (36, '"Wheel"');
INSERT INTO Status (StatusID, Status) VALUES (37, '"Throttle"');
INSERT INTO Status (StatusID, Status) VALUES (38, '"Steering"');
INSERT INTO Status (StatusID, Status) VALUES (39, '"Technical"');
INSERT INTO Status (StatusID, Status) VALUES (40, '"Electronics"');
INSERT INTO Status (StatusID, Status) VALUES (41, '"Broken wing"');
INSERT INTO Status (StatusID, Status) VALUES (42, '"Heat shield fire"');
INSERT INTO Status (StatusID, Status) VALUES (43, '"Exhaust"');
INSERT INTO Status (StatusID, Status) VALUES (44, '"Oil leak"');
INSERT INTO Status (StatusID, Status) VALUES (45, '"+11 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (46, '"Wheel rim"');
INSERT INTO Status (StatusID, Status) VALUES (47, '"Water leak"');
INSERT INTO Status (StatusID, Status) VALUES (48, '"Fuel pump"');
INSERT INTO Status (StatusID, Status) VALUES (49, '"Track rod"');
INSERT INTO Status (StatusID, Status) VALUES (50, '"+17 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (51, '"Oil pressure"');
INSERT INTO Status (StatusID, Status) VALUES (128, '"+42 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (53, '"+13 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (54, '"Withdrew"');
INSERT INTO Status (StatusID, Status) VALUES (55, '"+12 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (56, '"Engine fire"');
INSERT INTO Status (StatusID, Status) VALUES (129, '"Engine misfire"');
INSERT INTO Status (StatusID, Status) VALUES (58, '"+26 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (59, '"Tyre puncture"');
INSERT INTO Status (StatusID, Status) VALUES (60, '"Out of fuel"');
INSERT INTO Status (StatusID, Status) VALUES (61, '"Wheel nut"');
INSERT INTO Status (StatusID, Status) VALUES (62, '"Not classified"');
INSERT INTO Status (StatusID, Status) VALUES (63, '"Pneumatics"');
INSERT INTO Status (StatusID, Status) VALUES (64, '"Handling"');
INSERT INTO Status (StatusID, Status) VALUES (65, '"Rear wing"');
INSERT INTO Status (StatusID, Status) VALUES (66, '"Fire"');
INSERT INTO Status (StatusID, Status) VALUES (67, '"Wheel bearing"');
INSERT INTO Status (StatusID, Status) VALUES (68, '"Physical"');
INSERT INTO Status (StatusID, Status) VALUES (69, '"Fuel system"');
INSERT INTO Status (StatusID, Status) VALUES (70, '"Oil line"');
INSERT INTO Status (StatusID, Status) VALUES (71, '"Fuel rig"');
INSERT INTO Status (StatusID, Status) VALUES (72, '"Launch control"');
INSERT INTO Status (StatusID, Status) VALUES (73, '"Injured"');
INSERT INTO Status (StatusID, Status) VALUES (74, '"Fuel"');
INSERT INTO Status (StatusID, Status) VALUES (75, '"Power loss"');
INSERT INTO Status (StatusID, Status) VALUES (76, '"Vibrations"');
INSERT INTO Status (StatusID, Status) VALUES (77, '"107% Rule"');
INSERT INTO Status (StatusID, Status) VALUES (78, '"Safety"');
INSERT INTO Status (StatusID, Status) VALUES (79, '"Drivetrain"');
INSERT INTO Status (StatusID, Status) VALUES (80, '"Ignition"');
INSERT INTO Status (StatusID, Status) VALUES (81, '"Did not qualify"');
INSERT INTO Status (StatusID, Status) VALUES (82, '"Injury"');
INSERT INTO Status (StatusID, Status) VALUES (83, '"Chassis"');
INSERT INTO Status (StatusID, Status) VALUES (84, '"Battery"');
INSERT INTO Status (StatusID, Status) VALUES (85, '"Stalled"');
INSERT INTO Status (StatusID, Status) VALUES (86, '"Halfshaft"');
INSERT INTO Status (StatusID, Status) VALUES (87, '"Crankshaft"');
INSERT INTO Status (StatusID, Status) VALUES (88, '"+10 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (89, '"Safety concerns"');
INSERT INTO Status (StatusID, Status) VALUES (90, '"Not restarted"');
INSERT INTO Status (StatusID, Status) VALUES (91, '"Alternator"');
INSERT INTO Status (StatusID, Status) VALUES (92, '"Underweight"');
INSERT INTO Status (StatusID, Status) VALUES (93, '"Safety belt"');
INSERT INTO Status (StatusID, Status) VALUES (94, '"Oil pump"');
INSERT INTO Status (StatusID, Status) VALUES (95, '"Fuel leak"');
INSERT INTO Status (StatusID, Status) VALUES (96, '"Excluded"');
INSERT INTO Status (StatusID, Status) VALUES (97, '"Did not prequalify"');
INSERT INTO Status (StatusID, Status) VALUES (98, '"Injection"');
INSERT INTO Status (StatusID, Status) VALUES (99, '"Distributor"');
INSERT INTO Status (StatusID, Status) VALUES (100, '"Driver unwell"');
INSERT INTO Status (StatusID, Status) VALUES (101, '"Turbo"');
INSERT INTO Status (StatusID, Status) VALUES (102, '"CV joint"');
INSERT INTO Status (StatusID, Status) VALUES (103, '"Water pump"');
INSERT INTO Status (StatusID, Status) VALUES (104, '"Fatal accident"');
INSERT INTO Status (StatusID, Status) VALUES (105, '"Spark plugs"');
INSERT INTO Status (StatusID, Status) VALUES (106, '"Fuel pipe"');
INSERT INTO Status (StatusID, Status) VALUES (107, '"Eye injury"');
INSERT INTO Status (StatusID, Status) VALUES (108, '"Oil pipe"');
INSERT INTO Status (StatusID, Status) VALUES (109, '"Axle"');
INSERT INTO Status (StatusID, Status) VALUES (110, '"Water pipe"');
INSERT INTO Status (StatusID, Status) VALUES (111, '"+14 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (112, '"+15 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (113, '"+25 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (114, '"+18 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (115, '"+22 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (116, '"+16 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (117, '"+24 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (118, '"+29 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (119, '"+23 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (120, '"+21 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (121, '"Magneto"');
INSERT INTO Status (StatusID, Status) VALUES (122, '"+44 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (123, '"+30 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (124, '"+19 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (125, '"+46 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (126, '"Supercharger"');
INSERT INTO Status (StatusID, Status) VALUES (127, '"+20 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (130, '"Collision damage"');
INSERT INTO Status (StatusID, Status) VALUES (131, '"Power Unit"');
INSERT INTO Status (StatusID, Status) VALUES (132, '"ERS"');
INSERT INTO Status (StatusID, Status) VALUES (133, '"+49 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (134, '"+38 Laps"');
INSERT INTO Status (StatusID, Status) VALUES (135, '"Brake duct"');
INSERT INTO Status (StatusID, Status) VALUES (136, '"Seat"');
INSERT INTO Status (StatusID, Status) VALUES (137, '"Damage"');
INSERT INTO Status (StatusID, Status) VALUES (138, '"Debris"');
INSERT INTO Status (StatusID, Status) VALUES (139, '"Illness"');
INSERT INTO Status (StatusID, Status) VALUES (140, '"Undertray"');
INSERT INTO Status (StatusID, Status) VALUES (141, '"Cooling system"');
INSERT INTO Status (StatusID, Status) VALUES (null, 'null');